org.gradle.jvmargs=-Xmx1G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1.2]
neo_version=26.1.2.36-beta

mod_id=redstone_enchants
mod_name=Redstone-chans Enchantment Expansion
mod_license=MIT
mod_version=1.2.1-mc26.1.2-neoforge
mod_group_id=com.chinaex123.redstone_enchants
